services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: traffic-tracker-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: traffic_tracker
      MYSQL_USER: tracker_user
      MYSQL_PASSWORD: tracker_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./api/db.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - traffic-tracker

  # PHP-FPM
  php:
    build:
      context: ./api
      dockerfile: Dockerfile.php
    container_name: traffic-tracker-php
    restart: unless-stopped
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: traffic_tracker
      DB_USER: tracker_user
      DB_PASSWORD: tracker_password
    depends_on:
      - database
    volumes:
      - ./api:/var/www/html
    networks:
      - traffic-tracker

  # Nginx for API
  api:
    image: nginx:alpine
    container_name: traffic-tracker-api
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./api:/var/www/html
      - ./api/.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - traffic-tracker

  # React Frontend Dashboard
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: traffic-tracker-frontend
    restart: unless-stopped
    ports:
      - "3000:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8001/api/v1
      VITE_API_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImFkbWluQHlvbWFsaS5jb20iLCJpYXQiOjE3NTI3MTkyMjYsImV4cCI6MTc1MjgwNTYyNn0.9E6Qf1beikY98s3knTQV1IYarHFbLWNZaO_ABZKXBy4"
      VITE_DOMAIN_ID: "1"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - traffic-tracker

  # Tracker HTML Example
  tracker:
    image: nginx:alpine
    container_name: traffic-tracker-tracker
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./tracker:/usr/share/nginx/html
    networks:
      - traffic-tracker

volumes:
  mysql_data:
    driver: local

networks:
  traffic-tracker:
    driver: bridge